services:
  - type: web
    name: chess-betting-backend
    env: node
    plan: starter
    rootDirectory: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
